### ISSUE TITLE
Depth and Greenscreen are rendering upside down 

### ISSUE THREAD

**Issue by whereisboneman** [thatshaman/ReShadeShaders#1]
![image](https://user-images.githubusercontent.com/110568599/182706966-126bc3d0-f560-4186-8d8d-cc373f9e1251.png)

**Comment by thatshaman** [comment]
Could you check your settings to what RESHADE_DEPTH_INPUT_IS_REVERSED is set and if changing it to either:

RESHADE_DEPTH_INPUT_IS_REVERSED=1

or

RESHADE_DEPTH_INPUT_IS_REVERSED=0

Solves this?
